# Set to your project's Clarinet config file
clarinet = "./demo-project/Clarinet.toml"

# Set where you'd like Deno types output.
# Comment or remove section to skip Deno types
# [deno]
# `output` can be a directory or a folder.
# output = "demo-project/deno/index.ts"

# Set where you'd like ESM types output.
# Comment or remove section to skip ESM types
[esm]
# `output` can be a directory or a folder.
output = "demo-project/esm/index.ts"

# `esm.after` - script to run after ESM types are generated.
# examples:
# after = "yarn prettier ./esm/index.ts"
# after = "echo 'yay'"
