import { readFile, writeFile } from 'fs/promises';

async function run() {
  const tomlInit = (await readFile('./scripts/init-config.toml', 'utf-8')).replaceAll('`', '\\`');

  const tomlCode = `// This file is automatically generated from the
// contents of \`./init-config.toml\`

export const tomlInit = \`
${tomlInit}
\`;
`;
  await writeFile('./src/generated/init-config.ts', tomlCode, 'utf-8');
}

run()
  .catch(console.error)
  .finally(() => {
    process.exit();
  });
