/** biome-ignore-all lint/style/useTrimStartEnd: suppressed */
import { readFile, writeFile } from 'node:fs/promises';
import { ConfigFile } from '../src/config';

async function run() {
  const tomlInit = (
    await readFile('./scripts/init-config.toml', 'utf-8')
  ).replaceAll('`', '\\`');

  const tomlCode = `// This file is automatically generated from the
// contents of \`./init-config.toml\`

export const tomlInit = \`
${tomlInit}
\`;
`;
  await writeFile('./src/generated/init-config.ts', tomlCode, 'utf-8');

  const packageJsonTxt = await readFile('./package.json', 'utf-8');
  const packageJson = JSON.parse(packageJsonTxt) as {
    version: string;
  };
  const { version } = packageJson;

  const versionCode = `// This file is automatically generated from the
// version in \`package.json\`

export const version = '${version}';
`;
  await writeFile('./src/generated/version.ts', versionCode, 'utf-8');

  const configSchema = ConfigFile.toJsonSchema();

  await writeFile(
    './scripts/config-schema.json',
    JSON.stringify(configSchema, null, 2),
    'utf-8'
  );
}

run()
  .catch(console.error)
  .finally(() => {
    process.exit();
  });
