name: Pull Request
on: [pull_request, workflow_dispatch]

jobs:
  code_checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm exec vp run build:packages
      - name: Check
        run: pnpm exec vp check
      - name: Type checks
        run: pnpm exec vp run typecheck
      - name: Tests
        run: pnpm exec vp run test
